### ISSUE TITLE
Imperfections on the Plating

### ISSUE THREAD

**Issue by bnichol** [sinara-hw/Booster#92] opened 2018-09-10 15:44 UTC
cloudy white marks started appearing on the plating as shown in the picture
![plating](https://user-images.githubusercontent.com/26362933/45308159-b8daf500-b518-11e8-9eaf-b902ebb53130.JPG)

**Comment by gkasprow** [comment] 2018-09-10 18:43
It looks like the plating process was faulty. This should be possible to fix. Let's wait and observe what happens. Later on we will replace the modules and ask the company who did plating for repair

**Comment by hartytp** [comment] 2018-09-10 19:38
Sounds good. Shouldn't this have been picked up by QC at TechnoSystems?

**Comment by gkasprow** [comment] 2018-09-10 20:48
It looks like it was not immediate effect. Probably they didn't wash it before plating, so electrochemical process continues and such marks will grow and cover whole surface after a few days.

**Comment by hartytp** [comment] 2018-09-10 21:03
Okay, I didn't know that cold happen. @bnichol if you get the chance, could you look at this again in a week or two to see if the problem is spreading?

**Comment by hartytp** [comment] 2018-09-11 14:35
I'll close this issue now, as there is no immediate action to be taken.

@gkasprow will you report this to TechnoSystem, or shall I?

**Closed by hartytp** 2018-09-11 14:35 UTC
