### ISSUE TITLE
Use MAC address from EEPROM

### ISSUE THREAD

**Issue by cjbe** [sinara-hw/Booster#156] opened 2019-03-06 21:10 UTC
The v1.3 Booster we have received seems to have a non-unique MAC address (0008dcabcdef) - shouldn't there be a unique MAC address in the EEPROM?

**Comment by wizath** [comment] 2019-03-06 21:28
It should, I'll check it tomorrow

**Comment by wizath** [comment] 2019-03-06 21:51
Ahh, last issue was that mainboard EEPROM was not equipped with UUID feature. But anyway if nothing is saved in EEPROM, it should use CPU UUID for setting MAC address.

Could you check if MAC address is equal to bytes [6:11] from UUID? VCP command is `devid`

**Comment by cjbe** [comment] 2019-03-06 22:02
```
> devid
[devid] 002600213436470832383539
```
and
```
> ifconfig
[log] ===== W5500 NET CONF : Static =====
[log]   MAC:    00:08:DC:AB:CD:EF
[log]   IP:     192.168.1.10
[log]   GW:     192.168.1.1
```

**Comment by wizath** [comment] 2019-03-06 22:46
Ok, found it. That's related to DHCP client bug that fails after some time and is programmed to set default settings with this MAC address. I'll change it to try indefinitely when error occurs and it should fix it.

**Comment by wizath** [comment] 2019-03-06 22:47
btw, in v1.3 new EEPROM was added with UUID-64 so i'll add support for reading that into MAC address.

**Comment by cjbe** [comment] 2019-03-06 22:47
Awesome - thanks!

**Comment by wizath** [comment] 2019-03-29 15:22
https://github.com/sinara-hw/Booster/issues/98#issuecomment-478037725
Fixed. Could you check if this is working on your device, since there is an issue with EEPROMS (https://github.com/sinara-hw/Booster/issues/187)

**Comment by hartytp** [comment] 2019-04-09 11:58
What do you want me to check?

**Comment by wizath** [comment] 2019-04-09 12:02
You can try to set custom MAC address then reboot and check if it was properly saved.

**Comment by hartytp** [comment] 2019-04-09 12:04
Should using the default MAC address from the EEPROM work now?

**Comment by wizath** [comment] 2019-04-09 12:05
It depends on hardware. If there are 2 EEPROMs mounted on mainboard there could be a problem.

**Comment by hartytp** [comment] 2019-04-09 12:07
How do I find out?

**Comment by wizath** [comment] 2019-04-09 12:15
Give me default MAC address that's displayed

**Comment by hartytp** [comment] 2019-04-09 12:25
how do I query that?

**Comment by wizath** [comment] 2019-04-09 12:28
ifconfig

**Comment by hartytp** [comment] 2019-04-10 11:42
ifconfig
[log] ===== W5500 NET CONF : DHCP =====
[log]	MAC:	80:1F:12:56:19:BC
[log]	IP:	0.0.0.0
[log]	GW:	0.0.0.0
[log]	SN:	0.0.0.0
[log] =======================================

**Comment by hartytp** [comment] 2019-04-10 11:42
Is that what you expect?

**Comment by wizath** [comment] 2019-04-10 11:46
Looks good. Can you change MAC address (using `macaddr` command like `macaddr 11:22:33:44:55:66`) then reboot and check if it is saved properly. Then revert using `macaddr default`.

**Comment by hartytp** [comment] 2019-04-10 12:43
@wizath okay, the mac address is saved across reboots.

However...
```
> macconfig default
[macconfig] Default MAC address set
> 
> ifconfig
[log] ===== W5500 NET CONF : DHCP =====
[log]	MAC:	36:34:38:38:32:32
[log]	IP:	0.0.0.0
[log]	GW:	0.0.0.0
[log]	SN:	0.0.0.0
[log] =======================================
> 
```

when I reset it to the default address I get something odd...

**Comment by hartytp** [comment] 2019-04-10 12:45
also, cosmetic issue but `MAC address 80 set` is an odd comment. Shouldn't it print the whole MAC address there?

```
> macconfig 80:1F:12:56:19:BC
[macconfig] MAC address 80 set
> 
> ifconfig
[log] ===== W5500 NET CONF : DHCP =====
[log]	MAC:	80:1F:12:56:19:BC
[log]	IP:	0.0.0.0
[log]	GW:	0.0.0.0
[log]	SN:	0.0.0.0
[log] =======================================
> 
> 
```

**Comment by wizath** [comment] 2019-04-10 12:45
I'll add it to my list

**Comment by hartytp** [comment] 2019-04-10 12:49
Since `80:1F:12:56:19:BC` does not correspond to any vendor, I'd guess that it's something random that someone at Creotech picked...

**Comment by wizath** [comment] 2019-04-10 12:55
Hmm, maybe there is an issue with that dual EEPROM. But I can't confirm it right now.

**Comment by gkasprow** [comment] 2019-04-10 13:35
Isn't it MAC address taken from EEPROM EUI ?

**Comment by wizath** [comment] 2019-04-10 13:49
> Isn't it MAC address taken from EEPROM EUI ?
It is

**Comment by hartytp** [comment] 2019-04-10 14:07
Okay, so @gkasprow the big question is how do we get @wizath more hardware to test???

**Comment by hartytp** [comment] 2019-04-13 15:20
closing as duplicate of https://github.com/sinara-hw/Booster/issues/187

**Closed by hartytp** 2019-04-13 15:20 UTC
Labels: software
